import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('docs/screenshots',{recursive:true});
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});
const results=[];
try{
for(const mobile of [false,true]){
 const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:900},isMobile:mobile,hasTouch:mobile});
 const page=await context.newPage();
 const errors=[],requests=[];
 page.on('response',r=>{if(r.status()>=400)console.log('HTTP',r.status(),r.url());});
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 page.on('request',r=>requests.push(r.url()));
 await page.addInitScript(()=>{
  window.__contexts=[];
  const Native=window.AudioContext;
  window.AudioContext=class extends Native{constructor(...args){super(...args);this.__gains=[];window.__contexts.push(this);}createGain(){const gain=super.createGain();this.__gains.push(gain);return gain;}};
 });
 await page.goto(process.env.TEST_BASE_URL||'http://localhost:5173',{waitUntil:'networkidle'});
 assert(!requests.some(url=>url.includes('night-reference')), 'night image should be lazy');
 await page.screenshot({path:'docs/screenshots/'+(mobile?'mobile':'desktop')+'-opening.png'});
 await page.getByRole('button',{name:'点击进入森林'}).click();
 await page.waitForTimeout(1300);
 assert.equal(await page.evaluate(()=>window.__contexts[0].state),'running');
 const character=page.getByRole('button',{name:'和小黄人互动：挥手或跳跃'});
 await character.click();
 const animation=await character.getAttribute('data-state');
 assert(['jump','wave'].includes(animation));
 await character.click({force:true});
 assert.equal(await character.getAttribute('data-state'),animation,'animation must remain locked');
 await page.waitForTimeout(1600);
 assert.equal(await character.getAttribute('data-state'),'idle');
 for(const [value,expected] of [[0,'wave'],[.9,'jump']]){
  await page.evaluate(value=>{Math.random=()=>value;},value);
  await character.click();assert.equal(await character.getAttribute('data-state'),expected);
  await page.waitForTimeout(1600);assert.equal(await character.getAttribute('data-state'),'idle');
 }
 await page.waitForFunction(()=>document.querySelector('.eyelids')?.classList.contains('closed'),{},{timeout:7000});
 const light=page.getByRole('button',{name:'灯串熄灭，灯泡 4'});
 await light.click();
 assert.equal(await page.getByRole('button',{name:'灯串点亮，灯泡 4'}).getAttribute('aria-pressed'),'false');
 await page.getByRole('button',{name:'灯串点亮，灯泡 4'}).click();
 await page.getByRole('button',{name:'关闭音乐'}).click();
 assert.equal(await page.getByRole('button',{name:'打开音乐'}).getAttribute('aria-pressed'),'false');
 await page.waitForTimeout(1000);
 assert.equal(await page.evaluate(()=>window.__contexts[0].__gains[0].gain.value),0,'muting should fade master gain to zero');
 await page.getByRole('button',{name:'打开音乐'}).click();
 await page.waitForTimeout(1000);
 assert.equal(await page.evaluate(()=>window.__contexts[0].__gains[0].gain.value),1,'unmuting should restore gain');
 if(mobile){
  await page.locator('main').dispatchEvent('pointerdown',{pointerType:'touch',clientX:120,clientY:430});
  await page.locator('main').dispatchEvent('pointermove',{pointerType:'touch',clientX:250,clientY:480});
  await page.locator('main').dispatchEvent('pointerup',{pointerType:'touch'});
 }else await page.mouse.move(1350,800);
 await page.waitForTimeout(700);
 assert(Math.abs(await page.locator('main').evaluate(el=>Number(el.style.getPropertyValue('--px'))))>.2,'parallax should respond');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal overflow');
 await page.screenshot({path:'docs/screenshots/'+(mobile?'mobile':'desktop')+'-forest.png'});
 await page.getByRole('button',{name:'切换至萤火之森'}).click();
 await page.getByRole('heading',{name:'萤火之森'}).waitFor();
 await page.waitForTimeout(1300);
 assert(requests.some(url=>url.includes('night-reference')));
 await page.screenshot({path:'docs/screenshots/'+(mobile?'mobile':'desktop')+'-night.png'});
 await page.getByRole('button',{name:'切换至日光森林'}).click();
 await page.getByRole('heading',{name:'日光森林'}).waitFor();
 await page.waitForTimeout(1300);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
 await page.waitForTimeout(400);
 assert.equal(await page.evaluate(()=>window.__contexts[0].state),'suspended');
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});
 await page.waitForTimeout(400);
 assert.equal(await page.evaluate(()=>window.__contexts[0].state),'running');
 assert.deepEqual(errors,[]);
 results.push({viewport:mobile?'390x844':'1440x900',checks:['entry','audio unlocked','wave and jump branches, animation lock and idle return','random blink','master gain fade out/in','lights','music toggle','parallax','night lazy-load and round trip','background pause and resume','no horizontal overflow','no console errors'],passed:true});
 await context.close();
}
const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});
await page.goto(process.env.TEST_BASE_URL||'http://localhost:5173');
await page.getByRole('button',{name:'点击进入森林'}).click();
await page.waitForTimeout(400);
await page.mouse.move(380,700);
assert.equal(await page.locator('main').evaluate(el=>el.style.getPropertyValue('--px')),'0');
await page.getByRole('button',{name:'切换至萤火之森'}).click();
await page.getByRole('heading',{name:'萤火之森'}).waitFor();
results.push({reducedMotion:true,passed:true});
const failurePage=await browser.newPage();
await failurePage.route('**/night-reference.webp',route=>route.abort());
await failurePage.goto(process.env.TEST_BASE_URL||'http://localhost:5173');
await failurePage.getByRole('button',{name:'点击进入森林'}).click();
await failurePage.waitForTimeout(1300);
await failurePage.getByRole('button',{name:'切换至萤火之森'}).click();
await failurePage.getByRole('status').filter({hasText:'场景暂时没有加载成功'}).waitFor();
assert(await failurePage.getByRole('heading',{name:'日光森林'}).isVisible());
assert(await failurePage.getByRole('button',{name:'切换至萤火之森'}).isEnabled());
await failurePage.unroute('**/night-reference.webp');
await failurePage.getByRole('button',{name:'切换至萤火之森'}).click();
await failurePage.getByRole('heading',{name:'萤火之森'}).waitFor();
results.push({sceneLoadFailureAndRetry:true,passed:true});
await writeFile('docs/verification.json',JSON.stringify(results,null,2));
console.log(JSON.stringify(results,null,2));
}finally{await browser.close();}
